version: '3'
services:
  demo-1:
    build: ./demo-1
    volumes:
      - backup-volume:/usr/backup

  demo-2:
    build: ./demo-2
    volumes:
      - backup-volume:/usr/backup

  backup:
    build: ./backup
    volumes:
      - backup-volume:/usr/backup

volumes:
  backup-volume:
